# Source https://github.com/NOXCIS/Wiregate
services:
  wiregate:
    image: noxcis/wiregate:vidar
    container_name: wiregate
    hostname: wiregate
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun  
    restart: unless-stopped
    volumes:
      - /lib/modules:/lib/modules:ro 
      - $DOCKER_APPDATA_PATH/wiregate/iptable-rules:/WireGate/iptable-rules
      - $DOCKER_APPDATA_PATH/wiregate/wireguard:/etc/wireguard 
      - $DOCKER_APPDATA_PATH/wiregate/db:/WireGate/db
      - $DOCKER_APPDATA_PATH/wiregate/tor:/etc/tor/
      - $DOCKER_APPDATA_PATH/wiregate/master-key:/WireGate/master-key
      - $DOCKER_LOGS_PATH/wiregate:/WireGate/log/
    environment:
    #Config Path Optional
      #- WGDCONF_PATH=/etc/wireguard
    #Use Ofuscated Wireguard (AmneziaWG)
      - AMNEZIA_WG=true
    #Set Timezone
      - TZ=$TZ
    #Tor Settings
    ##########################################################
      - WGD_TOR_PROXY=true          #Enable Tor
      - WGD_TOR_EXIT_NODES={de}     #Ex. {gb},{fr}
      - WGD_TOR_DNS_EXIT_NODES={us}
      - WGD_TOR_BRIDGES=true        #Enable Tor Bridges
      - WGD_TOR_PLUGIN=snowflake    #OPTIONS webtunnel, obfs4, snowflake
    #WGDashboard Global Settings
    ##########################################################
      - WGD_WELCOME_SESSION=false   #Promts user accont creation after fist sign in. 
      - WGD_AUTH_REQ=false			  
      # - WGD_USER=admin
      # - WGD_PASS=admin
      - WGD_REMOTE_ENDPOINT=$TRAEFIK_HOSTNAME #your domain or ip
      - WGD_REMOTE_ENDPOINT_PORT=6060
      - WGD_PEER_ENDPOINT_ALLOWED_IP=0.0.0.0/0, ::/0
      - WGD_KEEP_ALIVE=21
      - WGD_MTU=1420
      - WGD_PORT_RANGE_STARTPORT=$WGD_PORT_RANGE_STARTPORT
      - APP_PREFIX=/wg

    #DNS Settings (Set To use Containers Above) You can use your own DNS
    ##########################################################
      - WGD_DNS=1.1.1.1
      - WGD_IPTABLES_DNS=1.1.1.1

    ports:
      - "$WGD_PORT_RANGE:4430-4433/udp" #UDP Interface Listen Ports
#      - 8000:80/tcp #Comment Out for full network lockdown, I.E only Accessible via VPN conttenction at http://wire.gate using config in generated ./config/master-key folder
    sysctls:        #Otherwise access the dashboard @ your-sever-ip/domain:6060
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiregate.rule=Host(`$TRAEFIK_HOSTNAME`) && ( PathPrefix(`/wg`) || PathPrefix(`/static`) )"
      - "traefik.http.routers.wiregate.entrypoints=websecure"
      - "traefik.http.services.wiregate.loadbalancer.server.port=6060"
      # Middlewares
      - "traefik.http.routers.wiregate.middlewares=chain-basic-auth@file"
    networks:
      wg:
        ipv4_address: 192.168.253.252
      traefik: {}
