name: vmutils

networks:
  default:
    driver: bridge
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

secrets:
  basic_auth_credentials:
    file: $BASIC_AUTH_CREDENTIALS_FILE

# IMPORTANT: This section MUST be last line in docker compose master file. All docker apps will echoe itself to the end of th master file with command like `sudo echo "  - compose/traefik3/docker-compose.yml" >> $DOCKER_COMPOSE_MASTER_FILE`.
include:
